# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go and c

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        apt-get install -y mingw-w64 make libssl-dev qt6-base-dev qt6-websockets-dev sudo libcap2-bin build-essential checkinstall zlib1g-dev libssl-dev
    #编译extender项目
    - name: build extender
      shell: bash
      run: |
        make extenders
    # #编译AdaptixServer项目
    # - uses: goreleaser/goreleaser-action@v4
    #   with:
    #     workdir: /home/runner/work/AdaptixC2/AdaptixC2/AdaptixServer
    #     args: "release --rm-dist --snapshot"
    #     version: 1.23.0
    #   env:
    #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    #     path: ./ # 可根据你的项目结构选择编译产物路径
        
    # - name: Zip files
    #   run: |
    #     cd ./AdaptixServer
    #     zip -r ./dist/AdaptixC2Server_archive.zip ./dist/AdaptixC2* #编译后的名字 ，在虚拟机默认文件会在dist目录下
    #     ls
    # - name: Upload binaries to release
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #      repo_token: ${{ secrets.GITHUB_TOKEN }}
    #      file: /home/runner/work/AdaptixC2/AdaptixC2/AdaptixServer/dist/AdaptixC2Server_archive.zip
    #      tag: ${{ github.ref }}
    #      overwrite: true
    #      file_glob: true
    #      draft: false #编译完成后 会自动发布到release
